In [2]:
import pandas as pd

In [8]:
dados = pd.read_csv('customer.csv')
dados.head()

,Unnamed: 0,Maior65Anos,Conjuge,Dependentes,MesesDeContrato,TelefoneFixo,VariasLinhasTelefonicas,ServicoDeInternet,SegurancaOnline,BackupOnline,SeguroNoDispositivo,SuporteTecnico,TVaCabo,StreamingDeFilmes,TipoDeContrato,PagamentoOnline,FormaDePagamento,ContaMensal,Churn
0,0,0,Sim,Nao,1,Nao,SemServicoTelefonico,DSL,Nao,Sim,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,29.85,Nao
1,1,0,Nao,Nao,34,Sim,Nao,DSL,Sim,Nao,Sim,Nao,Nao,Nao,UmAno,Nao,ChequePapel,56.95,Nao
2,2,0,Nao,Nao,2,Sim,Nao,DSL,Sim,Sim,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequePapel,53.85,Sim
3,3,0,Nao,Nao,45,Nao,SemServicoTelefonico,DSL,Sim,Nao,Sim,Sim,Nao,Nao,UmAno,Nao,DebitoEmConta,42.30,Nao
4,4,0,Nao,Nao,2,Sim,Nao,FibraOptica,Nao,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,70.70,Sim

In [9]:
dados.shape

(7043, 19)

In [10]:
traducao = {'Sim' : 1, 'Nao' : 0}

dadosmodificados = dados[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(traducao)
dadosmodificados

      Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0           1            0             0                1      0
1           0            0             1                0      0
2           0            0             1                1      1
3           0            0             0                0      0
4           0            0             1                1      1
...       ...          ...           ...              ...    ...
7038        1            1             1                1      0
7039        1            1             1                1      0
7040        1            1             0                1      0
7041        1            0             1                1      1
7042        0            0             1                1      0

[7043 rows x 5 columns]

In [11]:
dummies_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'], axis = 1))
dummies_dados

,Unnamed: 0,Maior65Anos,MesesDeContrato,ContaMensal,VariasLinhasTelefonicas_Nao,VariasLinhasTelefonicas_SemServicoTelefonico,VariasLinhasTelefonicas_Sim,ServicoDeInternet_DSL,ServicoDeInternet_FibraOptica,ServicoDeInternet_Nao,...,StreamingDeFilmes_Nao,StreamingDeFilmes_SemServicoDeInternet,StreamingDeFilmes_Sim,TipoDeContrato_DoisAnos,TipoDeContrato_Mensalmente,TipoDeContrato_UmAno,FormaDePagamento_CartaoDeCredito,FormaDePagamento_ChequeDigital,FormaDePagamento_ChequePapel,FormaDePagamento_DebitoEmConta
0,0,0,1,29.85,0,1,0,1,0,0,...,1,0,0,0,1,0,0,1,0,0
1,1,0,34,56.95,1,0,0,1,0,0,...,1,0,0,0,0,1,0,0,1,0
2,2,0,2,53.85,1,0,0,1,0,0,...,1,0,0,0,1,0,0,0,1,0
3,3,0,45,42.30,0,1,0,1,0,0,...,1,0,0,0,0,1,0,0,0,1
4,4,0,2,70.70,1,0,0,0,1,0,...,1,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,7038,0,24,84.80,0,0,1,1,0,0,...,0,0,1,0,0,1,0,0,1,0
7039,7039,0,72,103.20,0,0,1,0,1,0,...,0,0,1,0,0,1,1,0,0,0
7040,7040,0,11,29.60,0,1,0,1,0,0,...,1,0,0,0,1,0,0,1,0,0
7041,7041,1,4,74.40,0,0,1,0,1,0,...,1,0,0,0,1,0,0,0,1,0
7042,7042,0,66,105.65,1,0,0,0,1,0,...,0,0,1,1,0,0,0,0,0,1

In [16]:
dados_final = pd.concat([dadosmodificados, dummies_dados], axis = 1)
dados_final = dados_final.drop(['Unnamed: 0'], axis = 1)

dados_final.head()

,Conjuge,Dependentes,TelefoneFixo,PagamentoOnline,Churn,Maior65Anos,MesesDeContrato,ContaMensal,VariasLinhasTelefonicas_Nao,VariasLinhasTelefonicas_SemServicoTelefonico,...,StreamingDeFilmes_Nao,StreamingDeFilmes_SemServicoDeInternet,StreamingDeFilmes_Sim,TipoDeContrato_DoisAnos,TipoDeContrato_Mensalmente,TipoDeContrato_UmAno,FormaDePagamento_CartaoDeCredito,FormaDePagamento_ChequeDigital,FormaDePagamento_ChequePapel,FormaDePagamento_DebitoEmConta
0,1,0,0,1,0,0,1,29.85,0,1,...,1,0,0,0,1,0,0,1,0,0
1,0,0,1,0,0,0,34,56.95,1,0,...,1,0,0,0,0,1,0,0,1,0
2,0,0,1,1,1,0,2,53.85,1,0,...,1,0,0,0,1,0,0,0,1,0
3,0,0,0,0,0,0,45,42.30,0,1,...,1,0,0,0,0,1,0,0,0,1
4,0,0,1,1,1,0,2,70.70,1,0,...,1,0,0,0,1,0,0,1,0,0

In [17]:
dados_final.to_csv('customer-tratado.csv')